### ISSUE TITLE
Forge: 404 Not Found

### ISSUE THREAD

**Issue by ricardoboss** [LordDecapo/OREmodded#4]
I'm getting this error when starting:

    Name: forge-1.12.2-14.23.4.2705.jar
    URL: http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2705/forge-1.12.2-14.23.4.2705.jar
    Details: HTTP 404: Not Found
    Filename: 1afb-9f3f-06ac-480a
    Path: C:\TEMP\<user>\1afb-9f3f-06ac-480a

Any idea? I'm using the latest installer.

**Comment by ricardoboss** [comment]
Bump @LordDecapo

**Comment by YPIMG** [comment]
Installer officially dead. 👌

**Comment by ricardoboss** [comment]
I could look into the code and update the url for the forge binaries... Maybe later

**Comment by ricardoboss** [comment]
@qwerasd205

**Comment by qwerasd205** [comment]
I am no longer supporting the installer.

**Comment by LordDecapo** [comment]
Well if no one is actually going to do anything to keep up the stuff they
made... ill just kill modded very soon and go for a pack thats actually
managed

**Comment by qwerasd205** [comment]
The installer is not the pack, the pack is probably being maintained. I just stopped supporting the installer because of obnoxious demands and people not reporting their issues in a clear way which allowed me to fix them. But do whatever you want. (This issue should be closed now)

**Comment by davidgarland** [comment]
:clap:
